//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timeline
    {
        public int businessID { get; set; }
        public string customerID { get; set; }
        public System.DateTime entranceDate { get; set; }
        public System.DateTime entranceTime { get; set; }
        public Nullable<System.DateTime> exitTime { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
